# Generated by Django 2.1 on 2019-03-02 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertificates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sertificate',
            name='slug',
        ),
        migrations.AddField(
            model_name='sertificate',
            name='hours',
            field=models.IntegerField(null=True, verbose_name='Hours'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='author',
            field=models.TextField(null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='identificator',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(6)], verbose_name='Identificator'),
        ),
    ]
