# Generated by Django 2.1 on 2019-03-02 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertificates', '0002_auto_20190302_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sertificate',
            name='body',
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='identificator',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Number must be 6 digits', 'Invalid number')], verbose_name='Identificator'),
        ),
    ]
